services:
  opensearch:
    image: opensearchproject/opensearch:latest
    hostname: opensearch.lab
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch
      - discovery.seed_hosts=opensearch
      - cluster.initial_cluster_manager_nodes=opensearch
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD:-OpensearchPassword1@}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch:/usr/share/opensearch/data
    ports:
      - 0.0.0.0:9200:9200
      - 0.0.0.0:9600:9600
    networks:
      siem:
        ipv4_address: 10.90.0.10

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    hostname: opensearch-dashboards.lab
    ports:
      - 0.0.0.0:5601:5601
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch.lab:9200"]'
    networks:
      siem:
        ipv4_address: 10.90.0.20

networks:
  siem:
    driver: bridge
    ipam:
      config:
        - subnet: 10.90.0.0/24
          gateway: 10.90.0.1

volumes:
  opensearch: {}
