services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2'
    hostname: elasticsearch.lab
    restart: always
    ports:
      - 0.0.0.0:9200:9200
      - 0.0.0.0:9300:9300
    environment:
      - bootstrap.memory_lock=false
      - discovery.type=single-node
      - cluster.name=siem
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      siem:
        ipv4_address: 10.70.0.10

  logstash:
    image: 'docker.elastic.co/logstash/logstash-oss:8.17.0'
    hostname: logstash.lab
    restart: always
    ports:
      - 0.0.0.0:5000:5000
      - 0.0.0.0:9600:9600
      - 0.0.0.0:5044:5044
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    networks:
      siem:
        ipv4_address: 10.70.0.20

  kibana:
    image: 'docker.elastic.co/kibana/kibana-oss:7.10.2'
    hostname: kibana.lab
    restart: always
    ports:
      - 0.0.0.0:5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch.lab:9200
    networks:
      siem:
        ipv4_address: 10.70.0.30

networks:
  siem:
    driver: bridge
    ipam:
      config:
        - subnet: 10.70.0.0/24
          gateway: 10.70.0.1

volumes:
  elasticsearch_data: {}
