services:
  mongodb:
    image: 'mongo:7.0'
    hostname: mongodb.lab
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      siem:
        ipv4_address: 10.80.0.10

  datanode:
    image: 'graylog/graylog-datanode:6.0'
    hostname: datanode.lab
    environment:
      GRAYLOG_DATANODE_NODE_ID_FILE: "/var/lib/graylog-datanode/node-id"
      GRAYLOG_DATANODE_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET:-rRmLbgMSGNUd8AJjyuyj0I0x3LCJna3tJOp9LnqQqwuNDWaMWlCDyUeGlh21AxnSwR9hvyISpMrm51ONOUNH1459VfOJEVvK}" # How to generate: pwgen -N 1 -s 96
      GRAYLOG_DATANODE_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2:-c0b594560e0042ba216e754fef9247e72464f06e4ca0af7d1c2112dc2401281f}" # Password: graylogpassword | How to generate: echo -n graylogpassword | shasum -a 256
      GRAYLOG_DATANODE_MONGODB_URI: "mongodb://mongodb.lab:27017/graylog"
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 0.0.0.0:8999:8999/tcp
      - 0.0.0.0:9200:9200/tcp
      - 0.0.0.0:9300:9300/tcp
    volumes:
      - graylog-datanode:/var/lib/graylog-datanode
    restart: always
    networks:
      siem:
        ipv4_address: 10.80.0.20

  graylog:
    hostname: graylog.lab
    image: 'graylog/graylog:6.0'
    depends_on:
      mongodb:
        condition: 'service_started'
    entrypoint: '/usr/bin/tini -- /docker-entrypoint.sh'
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/data/node-id"
      GRAYLOG_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET:-rRmLbgMSGNUd8AJjyuyj0I0x3LCJna3tJOp9LnqQqwuNDWaMWlCDyUeGlh21AxnSwR9hvyISpMrm51ONOUNH1459VfOJEVvK}" # How to generate: pwgen -N 1 -s 96
      GRAYLOG_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2:-c0b594560e0042ba216e754fef9247e72464f06e4ca0af7d1c2112dc2401281f}" # Password: graylogpassword | How to generate: echo -n graylogpassword | shasum -a 256
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb.lab:27017/graylog"
    ports:
      - 0.0.0.0:5044:5044/tcp   # Beats
      - 0.0.0.0:5140:5140/udp   # Syslog
      - 0.0.0.0:5140:5140/tcp   # Syslog
      - 0.0.0.0:5555:5555/tcp   # RAW TCP
      - 0.0.0.0:5555:5555/udp   # RAW TCP
      - 0.0.0.0:9001:9000/tcp   # Server API
      - 0.0.0.0:12201:12201/tcp # GELF TCP
      - 0.0.0.0:12201:12201/udp # GELF UDP
      - 0.0.0.0:13301:13301/tcp # Forwarder data
      - 0.0.0.0:13302:13302/tcp # Forwarder config
    volumes:
      - graylog_data:/usr/share/graylog/data/data
      - graylog_journal:/usr/share/graylog/data/journal
    restart: always
    networks:
      siem:
        ipv4_address: 10.80.0.30

networks:
  siem:
    driver: bridge
    ipam:
      config:
        - subnet: 10.80.0.0/24
          gateway: 10.80.0.1

volumes:
  mongodb_data: {}
  graylog-datanode: {}
  graylog_data: {}
  graylog_journal: {}
